basePath: /
definitions:
  api.Currency:
    properties:
      abbreviation:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  api.ErrorStruct:
    properties:
      status:
        type: string
    type: object
  api.ExchangeRate:
    properties:
      base_currency:
        $ref: '#/definitions/api.Currency'
      currency:
        $ref: '#/definitions/api.Currency'
      id:
        type: string
      rate:
        type: number
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: biv_1998@mail.ru
    name: Ilya
  description: Swagger API for Golang Project Exchanger
  title: Exchanger
  version: "1.0"
paths:
  /currencies/:
    get:
      description: Get name, description and abbreviation for all currencies in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Currency'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorStruct'
      summary: currencies
      tags:
      - Currencies
  /rates/:
    get:
      description: Get name, description, abbreviation for currency, name, description
        and abbreviation for base currency, time and rate
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.ExchangeRate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorStruct'
      summary: rates
      tags:
      - Rates
swagger: "2.0"
